### ISSUE TITLE
Will there be Linux-Support?

### ISSUE THREAD

**Issue by budwol** [toroxx/vscode-avdmanager#10]
**Describe the Issue**
Path for AVD Manager / SDK Manager set but not working

**To Reproduce**
Linux --> Use AVDManager --> Start VS Code --> It will allways tell "AVD / SDK Manager not found/Not exist!"

**Expected behaviour**
Should work on Linux too

**Screenshots and output logs**
![image](https://github.com/toroxx/vscode-avdmanager/assets/137706895/f7b08eca-c1ed-4ec2-832b-5b4684465df8)

**Comment by JokingAboutLife** [comment]
I'm using this plugin on my Linux system without any problem.

**Comment by budwol** [comment]
hm... what am i doing wrong? 
![image](https://github.com/toroxx/vscode-avdmanager/assets/137706895/08785167-d5eb-4714-bb70-c5af331f1cf1)

**Comment by toroxx** [comment]
AVDManager required JAVA. Did you installed it?

Try the below commands on your VSCode terminal to check JAVA exists.
```
java -version
```

Also those commands which is the tool used to check the avdmanager and sdkmanager are installed correctly.
Replace <AVD Path> to yours. E.g. /home/wma/Android/Sdk/cmdline-tools/latest/bin
```
<AVD Path>/bin/avdmanager list avd

<AVD Path>/bin/sdkmanager --list_installed
```

**Comment by budwol** [comment]
```
java --version
openjdk 11.0.21 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```

```
~/Android/Sdk/tools/bin/avdmanager list avd
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
        at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        ... 5 more
```

starting the avd via android studio works ôO

**Comment by toroxx** [comment]
Here is the main reason. XmlSchema is not supported in Java that you had installed.
```
NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
```

Please install the jdk 8 and set JAVA_HOME to jdk8.

**Comment by budwol** [comment]
thanks a lot -  i'll try. issue closed.
